#!/usr/bin/env python
# encoding: utf-8
from distutils.core import setup, Extension
from distutils.cmd import Command
from distutils.command.build import build as build_cmd
import os, sys, datetime

version = "1.0b"

sources = ['src/__init__.c',
           
           'src/utils.c',
           'src/atoin.c',
           'src/cstr.c',
           'src/multipart.c',
           'src/sigsegv.c',
           'src/sha1.c',
           'src/file_info.c',
           'src/file_lock.c',
           
           'src/Application.c',
           'src/Request.c',
           'src/Response.c',
           'src/Stream.c',
           'src/URL.c',
           'src/SessionStore.c',
           'src/FileSessionStore.c',
           
              'src/xml/__init__.c']

os.chdir(os.path.join('.', os.path.dirname(__file__)))
py_version = ".".join([str(s) for s in sys.version_info[0:2]]) # "M.m"

# get revision
revision = ''
try:
  (child_stdin, child_stdout) = os.popen2('svnversion -n .')
  revision = child_stdout.read()
  version += '-r' + revision
except:
  pass

include_dirs = ['/usr/include/python%s' % py_version, # debian and others
                '/opt/local/include/python%s' % py_version, # bsd ports, mac ports, etc
                '/usr/local/include', # general
                '/usr/include']       # general

library_dirs = ['/opt/local/lib',
                '/usr/local/lib',
                '/usr/lib']

libraries = ['fcgi'] # to link with

runtime_library_dirs = []
extra_objects = []
define_macros = []
undef_macros = []
cflags = ' -Wall -include src/prefix.h'
sys_conf_h = 'src/system_config.h'
has_headers = [
  'fcntl.h',
  'sys/file.h',
  'sys/time.h',
  'sys/stat.h'
]

#---------------------------------------
# Commands

class apidocs(Command):
  description = 'Builds the documentation'
  user_options = []
  def initialize_options(self): pass
  def finalize_options(self): pass
  def run(self):
    try:
      import epydoc.markup.restructuredtext
      from epydoc import cli
      old_argv = sys.argv[1:]
      sys.argv[1:] = [
        '--config=doc/epydoc.conf',
        '--no-private', # epydoc bug, not read from config
        #'--verbose',
        '--simple-term'
      ]
      cli.cli()
      sys.argv[1:] = old_argv
    except ImportError:
      print 'epydoc not installed, skipping API documentation.'
  

def build_configure():
  import platform, re
  sys_conf_h_create = True
  try:
    if os.path.getmtime(sys_conf_h) > os.path.getmtime(__file__):
      sys_conf_h_create = False
  except os.error:
    pass
  if sys_conf_h_create:
    print 'Configuring build environment'
    f = open(sys_conf_h, "w")
    try:
      defname_re = re.compile('[^a-zA-Z_]')
      f.write("/* Generated by setup.py at %s */\n" % datetime.datetime.now())
      f.write("#ifndef SMISK_SYSTEM_CONFIG_H\n")
      f.write("#define SMISK_SYSTEM_CONFIG_H\n\n")
      for fn in has_headers:
        defname = defname_re.sub('_', fn).upper()
        sys.stdout.write('Looking for %s ... ' % fn)
        sys.stdout.flush()
        fn_found = False
        for dn in include_dirs:
          if os.path.isfile(os.path.join(dn, fn)):
            fn_found = True
            f.write("/* %s */\n" % fn)
            f.write("#ifndef HAVE_%s\n" % defname)
            f.write("#define HAVE_%s 1\n" % defname)
            f.write("#endif\n")
            break
        if not fn_found:
          sys.stdout.write("NOT ")
        sys.stdout.write("FOUND\n")
        sys.stdout.flush()
      f.write("\n#endif\n")
    finally:
      f.close()
  if '--debug' in sys.argv:
    define_macros.append(('SMISK_DEBUG', '1'))
    undef_macros.append('NDEBUG')
  else:
    if platform.machine().find('x86') != -1:
      cflags += ' -msse3'
      if platform.system() == 'Darwin':
        cflags += ' -mssse3'


#---------------------------------------
if sys.argv[1] == 'build':
  # write version.h
  f = open(os.path.abspath(os.path.join(os.path.dirname(__file__), "src/version.h")), "w")
  try:
    f.write("#ifndef SMISK_VERSION\n#define SMISK_VERSION \"%s\"\n#endif\n" % version)
    f.write("#ifndef SMISK_REVISION\n#define SMISK_REVISION \"%s\"\n#endif\n" % revision)
  finally: f.close()

  # configure
  build_configure()
  
  # set c flags
  if 'CFLAGS' in os.environ: os.environ['CFLAGS'] += cflags
  else: os.environ['CFLAGS'] = cflags

#---------------------------------------
setup (
  name = "smisk",
  version = version,
  description = "High-performance web service framework",
  long_description = """
Smisk is a simple, high-performance and scalable web service framework
written in C, but controlled by Python.

It is designed to widen the common bottle necks common in heavy-duty web
services.

The latest development version is available in
<a href="http://svn.hunch.se/smisk/trunk">the Smisk subversion repository</a>.
""",
  url = 'http://trac.hunch.se/smisk',
  download_url = 'http://trac.hunch.se/smisk/wiki/Download',
  author = 'Rasmus Andersson',
  author_email = 'rasmus@flajm.se',
  license = 'MIT',
  classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: POSIX :: Linux',
    'Operating System :: Unix',
    'Programming Language :: C',
    'Programming Language :: Python',
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Software Development :: Libraries :: Python Modules'],
  package_dir = {'': 'lib'},
  packages = ['smisk'],
  ext_modules = [Extension(
    name='smisk.core',
    sources=sources,
    include_dirs=include_dirs,
    library_dirs=library_dirs,
    runtime_library_dirs=runtime_library_dirs,
    libraries=libraries,
    extra_objects=extra_objects,
    define_macros=define_macros,
    undef_macros=undef_macros
  )],
  
  cmdclass={'apidocs': apidocs}
)
