# Lighttpd 1.4, http
'CONTENT_LENGTH': '359',
'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundarymKzNHjDXLFHAxJ54',
'DOCUMENT_ROOT': '/Users/rasmus/src/smisk/examples/core/input/',
'FCGI_ROLE': 'RESPONDER',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate'
'HTTP_ACCEPT_LANGUAGE': 'en-us',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_CONTENT_LENGTH': '359',
'HTTP_COOKIE': 'SID=dm5impd1pijgu143ng6p985cnoba4dg5',
'HTTP_HOST': 'localhost:8080',
'HTTP_REFERER': 'http://localhost:8080/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_5; en-us) AppleWebKit/525.27.1 (KHTML, like Gecko) Version/3.2.1 Safari/525.27.1',
'PATH_INFO': '',
'QUERY_STRING': '',
'REDIRECT_STATUS': '200',
'REMOTE_ADDR': '::1',
'REMOTE_PORT': '50012',
'REQUEST_METHOD': 'POST',
'REQUEST_URI': '/receive',
'SCRIPT_FILENAME': '/Users/rasmus/src/smisk/examples/core/input/receive',
'SCRIPT_NAME': '/receive',
'SERVER_ADDR': '::1',
'SERVER_NAME': 'localhost:8080',
'SERVER_PORT': '8080',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SOFTWARE': 'lighttpd/1.4.19 smisk/1.1.0',

# Lighttpd 1.4, https
'CONTENT_LENGTH': '51',
'CONTENT_TYPE': 'application/x-www-form-urlencoded',
'DOCUMENT_ROOT': '/Users/rasmus/src/smisk/examples/core/input/',
'FCGI_ROLE': 'RESPONDER',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTPS': 'on',
'HTTP_ACCEPT': 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate'
'HTTP_ACCEPT_LANGUAGE': 'en-us',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_CONTENT_LENGTH': '51',
'HTTP_COOKIE': 'SID=qrmslneg5t8uek1486sbeck1g01f46em',
'HTTP_HOST': 'localhost:8443',
'HTTP_REFERER': 'https://localhost:8443/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_5; en-us) AppleWebKit/525.27.1 (KHTML, like Gecko) Version/3.2.1 Safari/525.27.1',
'PATH_INFO': '',
'QUERY_STRING': '',
'REDIRECT_STATUS': '200',
'REMOTE_ADDR': '127.0.0.1',
'REMOTE_PORT': '49336',
'REQUEST_METHOD': 'POST',
'REQUEST_URI': '/receive',
'SCRIPT_FILENAME': '/Users/rasmus/src/smisk/examples/core/input/receive',
'SCRIPT_NAME': '/receive',
'SERVER_ADDR': '127.0.0.1',
'SERVER_NAME': 'localhost:8443',
'SERVER_PORT': '8443',
'SERVER_PROTOCOL': 'http/1.1',
'SERVER_SOFTWARE': 'lighttpd/1.4.19 smisk/1.1.0',


# Nginx 0.6, http:
'CONTENT_LENGTH': '',
'CONTENT_TYPE': '',
'DOCUMENT_ROOT': '/opt/local/html',
'DOCUMENT_URI': '/',
'FCGI_ROLE': 'RESPONDER',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate'
'HTTP_ACCEPT_LANGUAGE': 'en-us',
'HTTP_CACHE_CONTROL': 'max-age=0',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'SID=onqrdc4vtj2s22tp7di0m5bugr55n9ac',
'HTTP_HOST': 'localhost:8081',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_5; en-us) AppleWebKit/525.27.1 (KHTML, like Gecko) Version/3.2.1 Safari/525.27.1',
'QUERY_STRING': '',
'REMOTE_ADDR': '127.0.0.1',
'REMOTE_PORT': '49711',
'REQUEST_METHOD': 'GET',
'REQUEST_URI': '/',
'SCRIPT_FILENAME': '/dev/null',
'SCRIPT_NAME': '/',
'SERVER_ADDR': '127.0.0.1',
'SERVER_NAME': 'localhost',
'SERVER_PORT': '8081',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SOFTWARE': 'nginx/0.6.32 smisk/1.1.0',
