#!/bin/bash
# Test working copy
for PV in  2.4  2.5  2.6  2.7 ; do
  if (which python$PV>/dev/null); then
    echo "$0:" "Building and testing working copy Smisk with Python $PV"
    rm -rf build/lib.*
    python$PV setup.py build -f > /dev/null || exit 1
    PYTHONPATH="$(echo $(pwd)/build/lib.*-$PV)" python$PV -c 'import smisk.test as t;t.test(verbosity=0)' || exit 1
  fi
done
